### ISSUE TITLE
ValueError: mutable default <class 'numpy.ndarray'> for field player_pose is not allowed: use default_factory

### ISSUE THREAD

**Issue by YtengTan** [amacati/SoulsGym#45]
Hello,

Thanks for providing this amazing gym package!

While I tried to run the script provided in the [documentation](https://soulsgym.readthedocs.io/en/latest/getting_started/gym.html).

It raises `ValueError: mutable default <class 'numpy.ndarray'> for field player_pose is not allowed: use default_factory`.

Complete prompt output:

```
(dsrl) D:\Lab\dark_souls_rl\SoulsGym\tests>python test_api.py

Traceback (most recent call last):
  File "D:\Lab\dark_souls_rl\SoulsGym\tests\test_api.py", line 6, in <module>
    env = gym.make("SoulsGymIudex-v0")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\dsrl\Lib\site-packages\gymnasium-0.28.1-py3.11.egg\gymnasium\envs\registration.py", line 755, in make
    env_creator = load_env_creator(env_spec.entry_point)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\dsrl\Lib\site-packages\gymnasium-0.28.1-py3.11.egg\gymnasium\envs\registration.py", line 553, in load_env_creator
    mod = importlib.import_module(mod_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\dsrl\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ProgramData\Anaconda3\envs\dsrl\Lib\site-packages\soulsgym-0.1.0-py3.11.egg\soulsgym\envs\iudex_env.py", line 23, in <module>
    from soulsgym.envs.soulsenv import SoulsEnv, SoulsEnvDemo
  File "C:\ProgramData\Anaconda3\envs\dsrl\Lib\site-packages\soulsgym-0.1.0-py3.11.egg\soulsgym\envs\soulsenv.py", line 22, in <module>
    from soulsgym.core.logger import Logger
  File "C:\ProgramData\Anaconda3\envs\dsrl\Lib\site-packages\soulsgym-0.1.0-py3.11.egg\soulsgym\core\logger.py", line 12, in <module>
    from soulsgym.core.game_state import GameState
  File "C:\ProgramData\Anaconda3\envs\dsrl\Lib\site-packages\soulsgym-0.1.0-py3.11.egg\soulsgym\core\game_state.py", line 14, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\dsrl\Lib\dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\dsrl\Lib\dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\dsrl\Lib\dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\Anaconda3\envs\dsrl\Lib\dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'numpy.ndarray'> for field player_pose is not allowed: use default_factory
```

FYI, this is my environment info:
OS: Windows 10, Python: 3.11.2
```
Package              Version
-------------------- ---------
certifi              2022.12.7
cloudpickle          2.2.1
cloudpickle          2.2.1
colorama             0.4.6
Farama-Notifications 0.0.4
Farama-Notifications 0.0.4
gymnasium            0.28.1
gymnasium            0.28.1
iniconfig            2.0.0
jax-jumpy            1.0.0
jax-jumpy            1.0.0
mss                  8.0.3
mss                  8.0.3
numpy                1.24.2
numpy                1.24.2
packaging            23.1
pip                  23.0.1
pluggy               1.0.0
psutil               5.9.4
psutil               5.9.4
Pymem                1.10.0
Pymem                1.10.0
pypiwin32            223
pytest               7.3.1
pywin32              306
PyYAML               6.0
PyYAML               6.0
setuptools           65.6.3
soulsgym             0.1.0
soulsgym             0.1.0
typing_extensions    4.5.0
typing_extensions    4.5.0
wheel                0.38.4
wincertstore         0.2
```

How may I fix this?

Thank you!

**Comment by amacati** [comment]
I was able to reproduce this on my side, should be fixed in the new version
