### ISSUE TITLE
soulsgym no value

### ISSUE THREAD

**Issue by VeN0mYT** [amacati/SoulsGym#50]
iam new to this and i wanted to learn how to make ai like this but when i try the test.py its shows this error

 ERROR: The function received no value for the required argument: boss
Usage: test.py BOSS

For detailed information on this command, run:
  test.py --help 

which i dont understanding it

**Comment by amacati** [comment]
The script you are trying to use takes an argument for the boss ID. You can either invoke it with

`python test.py --boss Iudex`

or write your own minimal testing script:

```
import gymnasium
import soulsgym

env = gymnasium.make("SoulsGymIudex-v0")
obs, info = env.reset()

while True :
    action = env.action_space.sample()
    next_obs, reward, terminated, truncated, info = env.step(action)
    if terminated or truncated:
        break

env.close()
```

**Comment by VeN0mYT** [comment]
is there a specific version from the windowcapture library becuze when i try to run the sample it showes this error 

Traceback (most recent call last):
  File "g:\ai for ds3\SoulsGym-master\hah.py", line 3, in <module>
    from soulsgym.core.game_window.window_capture import WindowCapture 
  File "g:\ai for ds3\SoulsGym-master\soulsgym\core\game_window\__init__.py", line 3, in <module>
    from soulsgym.core.game_window.game_window import GameWindow       
  File "g:\ai for ds3\SoulsGym-master\soulsgym\core\game_window\game_window.py", line 20, in <module>
    from soulsgym.core.game_window.window_capture import WindowCapture 
  File "g:\ai for ds3\SoulsGym-master\soulsgym\core\game_window\window_capture.py", line 8, in <module>
    from soulsgym.core.game_window._C.window_capture import WindowCapture as _WindowCapture
ImportError: DLL load failed while importing window_capture: The specified module could not be found.

**Comment by amacati** [comment]
Have you installed the library via pip or directly from GitHub? In the latter case, you may want to try the dev branch. It replaces the previous window capture mechanism with [pixel_forge](https://github.com/amacati/pixel_forge) and should fix any issues with the game_window module.

**Comment by VeN0mYT** [comment]
i installed it as pip but i dont know how i get dev branch or how i can use pixel forge wiht it

**Comment by amacati** [comment]
You can download this repository with `git clone https://github.com/amacati/SoulsGym.git`, then go into the repository, switch to the dev branch (`git checkout dev`) and install it (`pip install .`).
